ProxyRequests Off

<VirtualHost *:3000>
    ProxyPass / http://app:3000/
    ProxyPassReverse / http://app:3000/

    Header onsuccess unset Refresh
    Header always unset Refresh
    Header onsuccess unset Link
    Header always unset Link

    Header onsuccess unset Content-Security-Policy
    Header always unset Content-Security-Policy
    Header always set Content-Security-Policy "default-src 'none';"
</VirtualHost>
