version: '3.8'

services:
  app:
    build: ./app
    restart: unless-stopped
  web:
    build: ./apache
    depends_on:
      - app
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
  bot:
    build: ./bot
    network_mode: "service:web"
    depends_on:
      - web
    restart: unless-stopped
