services:
  leakage:
    platform: linux/amd64
    container_name: leakage
    ports:
      - "8080:8080"
    build:
      context: ./prob/
    environment:
      FLAG: flag{REDACTED}
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: REDACTED
  bot:
    platform: linux/amd64
    container_name: leakage-bot
    ports:
      - "3000:3000"
    build:
      context: ./bot
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: REDACTED
